This is makeindex, version 2.15 [TeX Live 2013] (kpathsea + Thai support).
Scanning style file ./dsse.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file dsse.acn....done (23 entries accepted, 0 rejected).
Sorting entries....done (122 comparisons).
Generating output file dsse.acr....done (35 lines written, 0 warnings).
Output written in dsse.acr.
Transcript written in dsse.alg.
